// Renders the launch picker's lettering for the Steam Deck: deck/picker-art.txt.
// Run deck/make-picker-art.ps1 on Windows to regenerate it.
//
// The picker draws with nothing but Xlib, and the Deck's X server has no usable fonts for
// Cyrillic at a readable size. So every piece of text is rendered here once, as an 8-bit
// coverage mask - white text on black, the red channel kept - and the picker tints the masks
// into whatever colours it needs at run time. Sizes are in pixels on the Deck's 1280x800.

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Drawing.Text;
using System.IO;
using System.IO.Compression;
using System.Runtime.InteropServices;
using System.Text;

public static class PickerArt
{
    private const int ItemW = 520, ItemH = 62;

    public static void Write(string path)
    {
        StringBuilder sb = new StringBuilder();
        sb.Append("# Launch picker lettering, generated by make-picker-art.ps1: name width height base64(raw deflate of an 8-bit mask)\n");

        using (Font title = new Font("Segoe UI Semibold", 26f, FontStyle.Regular, GraphicsUnit.Pixel))
        using (Font item = new Font("Segoe UI", 22f, FontStyle.Regular, GraphicsUnit.Pixel))
        using (Font small = new Font("Segoe UI", 16f, FontStyle.Regular, GraphicsUnit.Pixel))
        using (Font footer = new Font("Segoe UI Semibold", 16f, FontStyle.Regular, GraphicsUnit.Pixel))
        {
            Add(sb, "title", Text("Выберите вариант запуска Pummel Party", title, 40));

            Add(sb, "item0", Item("Играть с модом", item, true));
            Add(sb, "item1", Item("Играть без мода", item, true));
            Add(sb, "item2", Item("Отмена", item, false));

            // Spaces around the number are left to the picker, which trims every piece to its ink.
            Add(sb, "hint_pre", Text("Без выбора через", small, 24));
            Add(sb, "hint_post_modded", Text("с — запуск с модом, как в прошлый раз", small, 24));
            Add(sb, "hint_post_vanilla", Text("с — запуск без мода, как в прошлый раз", small, 24));
            for (int d = 0; d <= 9; d++) Add(sb, "digit" + d, Text(d.ToString(), small, 24));

            Add(sb, "footer", Footer(footer));
        }

        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
    }

    // ------------------------------------------------------------------ drawing

    private static StringFormat Tight()
    {
        StringFormat f = (StringFormat)StringFormat.GenericTypographic.Clone();
        f.FormatFlags |= StringFormatFlags.MeasureTrailingSpaces | StringFormatFlags.NoWrap;
        return f;
    }

    private static Graphics Canvas(Bitmap b)
    {
        Graphics g = Graphics.FromImage(b);
        g.Clear(Color.Black);
        g.SmoothingMode = SmoothingMode.AntiAlias;
        g.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
        g.PixelOffsetMode = PixelOffsetMode.HighQuality;
        return g;
    }

    /// <summary>A line of text, as wide as it measures and <paramref name="height"/> tall.</summary>
    private static Bitmap Text(string s, Font font, int height)
    {
        int w;
        using (Bitmap probe = new Bitmap(4, 4))
        using (Graphics g = Graphics.FromImage(probe))
        using (StringFormat f = Tight())
            w = (int)Math.Ceiling(g.MeasureString(s, font, 4000, f).Width) + 2;

        Bitmap b = new Bitmap(Math.Max(w, 1), height, PixelFormat.Format32bppRgb);
        using (Graphics g = Canvas(b))
        using (StringFormat f = Tight())
        {
            float y = (height - font.GetHeight(g)) / 2f;
            g.DrawString(s, font, Brushes.White, 1f, y, f);
        }
        return b;
    }

    /// <summary>One row of the menu: its label, and the chevron Steam puts on rows that launch.</summary>
    private static Bitmap Item(string s, Font font, bool chevron)
    {
        Bitmap b = new Bitmap(ItemW, ItemH, PixelFormat.Format32bppRgb);
        using (Graphics g = Canvas(b))
        using (StringFormat f = Tight())
        {
            float y = (ItemH - font.GetHeight(g)) / 2f;
            g.DrawString(s, font, Brushes.White, 22f, y, f);
            if (chevron)
            {
                using (Pen p = new Pen(Color.White, 2.4f))
                {
                    p.StartCap = LineCap.Round; p.EndCap = LineCap.Round; p.LineJoin = LineJoin.Round;
                    float cx = ItemW - 30f, cy = ItemH / 2f;
                    g.DrawLines(p, new[] { new PointF(cx - 4f, cy - 8f), new PointF(cx + 4f, cy), new PointF(cx - 4f, cy + 8f) });
                }
            }
        }
        return b;
    }

    /// <summary>"(A) ВЫБРАТЬ   (B) НАЗАД": white button discs with the letter cut out, as Steam draws them.</summary>
    private static Bitmap Footer(Font font)
    {
        const int h = 34, disc = 26;
        string[] words = { "ВЫБРАТЬ", "НАЗАД" };
        string[] letters = { "A", "B" };

        float[] widths = new float[2];
        using (Bitmap probe = new Bitmap(4, 4))
        using (Graphics g = Graphics.FromImage(probe))
        using (StringFormat f = Tight())
            for (int i = 0; i < 2; i++) widths[i] = g.MeasureString(words[i], font, 4000, f).Width;

        int w = (int)Math.Ceiling(disc + 8 + widths[0] + 28 + disc + 8 + widths[1]) + 4;
        Bitmap b = new Bitmap(w, h, PixelFormat.Format32bppRgb);
        using (Graphics g = Canvas(b))
        using (StringFormat f = Tight())
        using (Font letter = new Font("Segoe UI Semibold", 15f, FontStyle.Regular, GraphicsUnit.Pixel))
        using (StringFormat centred = new StringFormat { Alignment = StringAlignment.Center, LineAlignment = StringAlignment.Center })
        {
            float x = 2f;
            for (int i = 0; i < 2; i++)
            {
                RectangleF r = new RectangleF(x, (h - disc) / 2f, disc, disc);
                g.FillEllipse(Brushes.White, r);
                g.DrawString(letters[i], letter, Brushes.Black, new RectangleF(r.X, r.Y + 0.5f, r.Width, r.Height), centred);
                x += disc + 8;
                g.DrawString(words[i], font, Brushes.White, x, (h - font.GetHeight(g)) / 2f, f);
                x += widths[i] + 28;
            }
        }
        return b;
    }

    // ------------------------------------------------------------------ output

    private static void Add(StringBuilder sb, string name, Bitmap b)
    {
        int w = b.Width, h = b.Height;
        byte[] mask = new byte[w * h];
        BitmapData data = b.LockBits(new Rectangle(0, 0, w, h), ImageLockMode.ReadOnly, PixelFormat.Format32bppRgb);
        try
        {
            byte[] row = new byte[data.Stride];
            for (int y = 0; y < h; y++)
            {
                Marshal.Copy(IntPtr.Add(data.Scan0, y * data.Stride), row, 0, data.Stride);
                for (int x = 0; x < w; x++) mask[y * w + x] = row[x * 4 + 2];   // red channel = coverage
            }
        }
        finally
        {
            b.UnlockBits(data);
            b.Dispose();
        }

        byte[] packed;
        using (MemoryStream ms = new MemoryStream())
        {
            using (DeflateStream z = new DeflateStream(ms, CompressionMode.Compress)) z.Write(mask, 0, mask.Length);
            packed = ms.ToArray();
        }
        sb.Append(name).Append(' ').Append(w).Append(' ').Append(h).Append(' ').Append(Convert.ToBase64String(packed)).Append('\n');
    }
}
