using System;
using System.IO;
using System.Text;
using HarmonyLib;
using MelonLoader;
using UnityEngine;

[assembly: MelonInfo(typeof(PummelCustomItems.Core), "PummelCustomItems", "0.45.0", "local")]
[assembly: MelonGame("Rebuilt Games", "Pummel Party")]

namespace PummelCustomItems
{
    public class Core : MelonMod
    {
        internal static Core Instance;

        public override void OnInitializeMelon()
        {
            Instance = this;
            LoggerInstance.Msg("=== PummelCustomItems loaded ===");
            LoggerInstance.Msg("Unity: " + Application.unityVersion);
            LoggerInstance.Msg("Game dir: " + Directory.GetCurrentDirectory());
            LoggerInstance.Msg("Debug keys: F7 = show health, F8 = hurt self, F9 = give all items, F10 = log items");

            // The game's own Debug.LogError output goes to Unity's Player.log, not here.
            // Mirror errors into the Melon log so a broken board action is visible at once.
            Application.logMessageReceived += OnUnityLog;
        }

        public override void OnDeinitializeMelon()
        {
            Application.logMessageReceived -= OnUnityLog;
        }

        private static string s_lastUnityError;
        private static int s_repeatCount;

        private static void OnUnityLog(string condition, string stackTrace, LogType type)
        {
            if (type != LogType.Error && type != LogType.Exception && type != LogType.Assert) return;
            if (Instance == null) return;

            // DoAction() can throw every single frame - collapse the spam.
            if (condition == s_lastUnityError)
            {
                s_repeatCount++;
                if (s_repeatCount == 10)
                    Instance.LoggerInstance.Warning("  (repeating every frame, further copies suppressed)");
                if (s_repeatCount >= 10) return;
            }
            else
            {
                s_lastUnityError = condition;
                s_repeatCount = 0;
            }

            Instance.LoggerInstance.Warning("[UNITY " + type + "] " + condition);
            if (!string.IsNullOrEmpty(stackTrace))
            {
                string[] lines = stackTrace.Split('\n');
                for (int i = 0; i < lines.Length && i < 6; i++)
                {
                    if (lines[i].Trim().Length > 0)
                        Instance.LoggerInstance.Warning("    " + lines[i].TrimEnd());
                }
            }
        }

        public override void OnUpdate()
        {
            DebugKeys.Update();
        }

        internal static void Log(string msg)
        {
            if (Instance != null) Instance.LoggerInstance.Msg(msg);
        }

        internal static void Warn(string msg)
        {
            if (Instance != null) Instance.LoggerInstance.Warning(msg);
        }
    }

    // ItemList.Setup() runs when the board builds its enabled-item table.
    // Best place to see the real, fully-loaded item data.
    [HarmonyPatch(typeof(ItemList), "Setup")]
    internal static class Patch_ItemList_Setup
    {
        private static bool s_dumped;

        private static void Postfix(ItemList __instance)
        {
            try
            {
                Core.Log("ItemList.Setup() ran. items=" + Len(__instance.items) +
                         " enabled=" + Len(__instance.enabledItems));

                if (s_dumped) return;
                s_dumped = true;

                var sb = new StringBuilder();
                sb.AppendLine("# Pummel Party item dump");
                sb.AppendLine("# generated by PummelCustomItems 0.1.0");
                sb.AppendLine();

                sb.AppendLine("## ItemList.items (" + Len(__instance.items) + ")");
                DumpArray(sb, __instance.items);

                sb.AppendLine();
                sb.AppendLine("## ItemList.enabledItems (" + Len(__instance.enabledItems) + ")");
                DumpArray(sb, __instance.enabledItems);

                sb.AppendLine();
                sb.AppendLine("## fallbackItem");
                DumpOne(sb, __instance.fallbackItem);

                string path = Path.Combine(Directory.GetCurrentDirectory(), "item_dump.txt");
                File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
                Core.Log("Item dump written to " + path);
            }
            catch (Exception e)
            {
                Core.Warn("dump failed: " + e);
            }
        }

        private static int Len(Array a)
        {
            return a == null ? -1 : a.Length;
        }

        private static void DumpArray(StringBuilder sb, ItemDetails[] arr)
        {
            if (arr == null) { sb.AppendLine("(null)"); return; }
            for (int i = 0; i < arr.Length; i++)
            {
                sb.AppendLine("--- [" + i + "] ---");
                DumpOne(sb, arr[i]);
            }
        }

        private static void DumpOne(StringBuilder sb, ItemDetails d)
        {
            if (d == null) { sb.AppendLine("(null)"); return; }

            sb.AppendLine("  enumReference   : " + d.enumReference);
            sb.AppendLine("  itemID          : " + d.itemID);
            sb.AppendLine("  itemIndex       : " + d.itemIndex);
            sb.AppendLine("  enabled         : " + d.enabled);
            sb.AppendLine("  isActive        : " + SafeIsActive(d));
            sb.AppendLine("  weaponSpaceItem : " + d.weaponSpaceItem);
            sb.AppendLine("  skipTurnAfterUse: " + d.skipTurnAfterUse);
            sb.AppendLine("  nameToken       : " + d.itemNameToken + "  (\"" + d.TranslatedName + "\")");
            sb.AppendLine("  descToken       : " + d.descriptionToken);
            sb.AppendLine("  netPrefabName   : " + d.netPrefabName);
            sb.AppendLine("  prefabPath      : " + d.prefabPath);
            sb.AppendLine("  prefab          : " + NameOf(d.prefab) + ItemComponentOf(d.prefab));
            sb.AppendLine("  recievePrefab   : " + NameOf(d.recievePrefab) + "  path=" + d.recievePrefabPath);
            sb.AppendLine("  heldPrefab      : " + NameOf(d.heldPrefab) + "  path=" + d.heldPrefabPath);
            sb.AppendLine("  heldBone        : " + d.heldBone);
            sb.AppendLine("  heldPos/Rot/Scl : " + d.heldPosition + " / " + d.heldRotation + " / " + d.heldScale);
            sb.AppendLine("  icon            : " + NameOf(d.icon) + "  tex=" + NameOf(d.iconTexture));
            sb.AppendLine("  isWorkshop      : " + d.isWorkshop + "  publishedFileId=" + d.publishedFileId);
        }

        private static string SafeIsActive(ItemDetails d)
        {
            try { return d.GetIsActive().ToString(); }
            catch (Exception e) { return "<error: " + e.GetType().Name + ">"; }
        }

        private static string NameOf(UnityEngine.Object o)
        {
            return o == null ? "(null)" : o.name;
        }

        // Which Item subclass actually drives this item?
        private static string ItemComponentOf(GameObject prefab)
        {
            if (prefab == null) return "";
            try
            {
                Item it = prefab.GetComponentInChildren<Item>(true);
                return it == null ? "  [no Item component]" : "  [Item class: " + it.GetType().Name + "]";
            }
            catch (Exception e)
            {
                return "  [component lookup failed: " + e.GetType().Name + "]";
            }
        }
    }
}
